#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

REDIRECT_conf="error_page 404 /xyz;\n\t location = /xyz {\n\troot /var/www/html;\n\tinternal;}\n"
FILE="/etc/nginx/sites-available/default"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/xyz
apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"

sudo sed -i "44i\ $REDIRECT_conf" "$FILE"

vi -c "=G" -c "wq" "$FILE"

sudo service nginx restart

