#!/usr/bin/env bash
#installs HAProxy version 2.0 with the following configurations:

apt-get -y update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get install -y haproxy=2.0.\*

cat << EOF >> /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server ${hostname} 100.26.235.153:80 check
    server ${hostname} 52.91.118.87:80 check
EOF

# Configure HAProxy to be managed via init script
sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

