#!/usr/bin/env bash
#installs HAProxy version 2.0 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get -y update
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0 -y
apt-get install -y haproxy=2.0.\*

cat << EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server ${hostname} 100.26.235.153:80 check
    server ${hostname} 52.91.118.87:80 check
EOF

# Configure HAProxy to be managed via init script
sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart
