#!/usr/bin/env bash
# Reloads Gunicorn.

# Use pgrep instead of ps and grep to find the process ID of gunicorn
systemctl status gunicorn | grep -oE 'Main PID: [0-9]+' | cut -d ' ' -f3 | xargs kill -HUP
